### PR TITLE
create todo list

### PR DESCRIPTION
**Pull request by MuzhdaN**
**Lesson 1.1**

- Created a new react project with with Vite.
- Installed required dependencies.
- Created a basic TodoList component.
- Defined an array of hardcoded todo items.
- Implemented a simple todo list.

### CODE REVIEW

**Comment by Lee3310gra** [comment]
No description available.

**Comment by Lee3310gra** [comment]
Provide proper description

**Comment by MuzhdaN** [comment]
@Lee3310gra 
Thank you for your comment.
Do you want me to create a new pull request, add a description and resubmit or edit the description for this PR?

**Comment by Lee3310gra** [comment]
Create a new pull request.

**Pull request merged**
